# Generated by Django 5.1 on 2024-08-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20201119_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscrm',
            old_name='Status_name',
            new_name='status_name',
        ),
    ]
